.\" Copyright (c) 2023 Paul Hewlett <phewlett76@gmail.com>
.\"
.\" Permission is granted to make and distribute verbatim copies of this
.\" manual provided the copyright notice and this permission notice are
.\" preserved on all copies.
.\"
.\" Permission is granted to copy and distribute modified versions of this
.\" manual under the conditions for verbatim copying, provided that the
.\" entire resulting derived work is distributed under the terms of a
.\" permission notice identical to this one.
.\"
.\" Since the Linux kernel and libraries are constantly changing, this
.\" manual page may be incorrect or out-of-date.  The author(s) assume no
.\" responsibility for errors or omissions, or for damages resulting from
.\" the use of the information contained herein.  The author(s) may not
.\" have taken the same level of care in the production of this manual,
.\" which is licensed free of charge, as they might when working
.\" professionally.
.\"
.\" Formatted or processed versions of this manual, if unaccompanied by
.\" the source, must acknowledge the copyright and authors of this work.
.\"
.TH TOPIARY 3 2013-05-16 "Linux" "Linux Programmer's Manual"
.SH NAME
.nf
topiary \- commandline interface to reading the /proc, /sys filesystems and other files
.fi
.SH SYNOPSIS
.nf
.BI "topiary <cmd> <options>"

.SH DESCRIPTION
.B topiary
reads system files (/proc, /sys and others).
.SS Commands
.P
.BR time
Prints performance metrics i.e. time taken to execute all modules broken down
into 
.B read time , map time, normalize time
and 
.B hash time.
.TP
.B read time
- time taken to read all data into RAM.
.TP
.B map time
- time taken to map raw data to an n-dimensional array.
.TP
.B normalize time
- time taken to convert raw data into normalized values such as %usage, seconds,
KiB and rates per second.
.TP
.B hash time
- time taken to create a hash map of the normalized data.
.SH RETURN VALUE
On success, all routines return zero.
Negative return values correspond to system error i.e. -errno.
Positive return values are described below.
.SH ERRORS
.TP
.B TOPIARY_OK
No error
.TP
.B TOPIARY_ERROR_MISMATCHED_STRINGS
Internal error - indicates an inconsistency in the error submodule
.TP
.B TOPIARY_ERROR_MALLOC
A malloc,realloc,calloc call has returned NULL.
.TP
.B TOPIARY_ERROR_ILLEGAL_ARG
A function argument is illegal. This includes cases where an argument
may have subfields that are illegal.
.TP
.B TOPIARY_ERROR_BASE_READ_OVERFLOW
Internal error to indicate when to grow buffers to accommodate the quantity
read.
This error is never returned to the user.
.TP
.B TOPIARY_ERROR_BASE_REGEX_FAILURE
The regular expression matcher has failed and is unable to extract the 
field data. Only some modules (
.B TOPIARY_SYS_DISKSECTORS & TOPIARY_PID_STAT
at time of writing ) use file globbing.
.TP
.B TOPIARY_ERROR_BASE_GLOB_FAILURE
The globbing expression matcher has failed and has returned no files matched.
Only some modules use file globbing.
.TP
.B TOPIARY_ERROR_NOT_FOUND
Requested group/key does not exist in the data read from the /proc and/or
/sys filesystems.
.TP
.B TOPIARY_ERROR_BASE_READ_SSIZE_MAX
Read request exceeds system limit SSIZE_MAX.
.SH ENVIRONMENT
The environment variable 
.B TOPIARY_TESTROOT
will be prepended to all files opened and closed by the
.B topiary
library. This environment variable is only set when testing the library against
a fixed set of /proc and /sys files located on a normal filesystem.
.SH FILES
.TP
TBD
.SH VERSIONS
.TP
TBD
.SH NOTES
Currently the key field of the hashtable produced by all the modules of topiary
has
a hardwired limit of 48 characters. When adding a new module please ensure that
any
generated keys are either not longer than this or increase the key length
limit and recompile the library.
.SH BUGS
The 
.B topiary
library was tested on Ubuntu 12.04 and 13.04 using valgrind and a standardised
test data set. 
The code is designed to work on earlier versions of the kernel. 
Some modules may not work and such cases should be reported to the author.
.SH EXAMPLE
\&
.nf

    topiary time
.fi
.SH SEE ALSO
.TP
TBD
.SH COLOPHON
A description of the project,
and information about reporting bugs,
can be found at
http://www.github.com/eccles/liblnxproc/.
