RELDIR=..
HDRS=lnxproc.h error.h map_limits.h base.h array.h map.h proc_cgroups.h
LIB=liblnxproc.so
SRCS=error.c map_limits.c base.c array.c map.c proc_cgroups.c
DIRS=

include $(RELDIR)/Makefile.generic

