RELDIR=..
PUBHDIR=../src/lnxproc
PUBHDRS=lnxproc.h db.h error.h results.h limits.h base.h vector.h array.h proc_cgroups.h proc_osrelease.h
HDRS=base_private.h vector_private.h array_private.h
LIB=liblnxproc
SRCS=error.c results.c limits.c vector.c array.c base.c proc_cgroups.c proc_osrelease.c
DIRS=
BIN=test-lnxproc

include $(RELDIR)/Makefile.generic

